### PR TITLE
Cleanup - add to RancherOnAks, refactor for RancherOnEks

### PR DESCRIPTION
**Pull request by bear454**
Cleanup now occurs in it's own controller (reducing a bunch of conditional logic). Recording is stored in the database as a set of env vars & a set of commands; these can be rendered out via an ERB template. 

* Less conditional logic
* Less configuration magic
* Less special conditions
* More obvious functions
:tada:

### CODE REVIEW

**Comment by bear454** [comment]
Holding until smaller PRs are merged in.

**Comment by bear454** [comment]
image

**Comment by bear454** [comment]
Screenshot 2023-02-14 at 19-45-11 SUSE Rancher Setup

**Review by jesusbv — APPROVED** [review]
LGTM

**Pull request merged**
